apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: lms-accesslibrary
  name: lms-accesslibrary
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-accesslibrary
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lms-accesslibrary
    spec:
      containers:
      - image: isabyasachi/lms-accesslibrary:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: lms-accesslibrary-service        
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lms-accesslibrary
  name: lms-accesslibrary
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: lms-accesslibrary
  sessionAffinity: None
  type: LoadBalancer
  
---