version: '3.7'

services:

  accesslibrary:
    image: isabyasachi/lms-accesslibrary:0.0.1-SNAPSHOT
    mem_limit: 1024m
    ports:
      - "8080:8080"
    networks:
      - lms-network

networks:
  lms-network: