-- Q1: Implement a query to get a list of all user and how many books each user has checked out.
SELECT * FROM T_ACCOUNT_USER A
INNER JOIN T_BOOK_ITEM BI ON A.ID = BI.ACCOUNT_USER_ID
INNER JOIN T_BOOK B ON BI.BOOK_ID = B.ID;

SELECT A.ID, A.NAME, COUNT(B.ID) AS NUM_BOOKS_CHECKED_OUT FROM T_ACCOUNT_USER A
LEFT JOIN T_BOOK_ITEM BI ON A.ID = BI.ACCOUNT_USER_ID
LEFT JOIN T_BOOK B ON BI.BOOK_ID = B.ID WHERE A.USER_TYPE='MEMBER' GROUP BY A.ID, A.NAME;

-- Q2: Implement a query to get list of all Librarian and how many Member they lended books and lended total number of books.
-- Sort the list in descending order of the number of Member a Librarian lends.
SELECT BI.LIBRARIAN_ID,LIB.NAME AS LIBRARIAN, COUNT(BI.BOOK_ID) AS TOTAL_CHECKEDOUT_BOOKS, COUNT(DISTINCT BI.ACCOUNT_USER_ID) AS TOTAL_CHECKEDOUT_USER FROM T_BOOK_ITEM BI
INNER JOIN T_ACCOUNT_USER LIB ON LIB.ID = BI.LIBRARIAN_ID
GROUP BY BI.LIBRARIAN_ID ORDER BY BI.ACCOUNT_USER_ID DESC;